[workspace]
resolver = "2"
members = ["quizx", "pybindings"]
default-members = ["quizx"]

[workspace.dependencies]
quizx = { path = "./quizx" }
num = "0.4.2"
approx = "0.5.1"
itertools = "0.12.1"
ndarray = "0.15.6"
openqasm = "0.1.2"
pyo3 = { version = "0.21" }
rand = "0.8.3"
rayon = "1.5.0"
regex = "1.4.3"
rustc-hash = "1.1.0"
derive_more = "0.99.17"
rstest = "0.19.0"
serde = "1.0.201"
serde_json = "1.0.116"
thiserror = "1.0.59"

[workspace.package]
version = "0.1.0"
authors = ["Aleks Kissinger <aleks0@gmail.com>"]
edition = "2021"
rust-version = "1.75"
homepage = "https://github.com/Quantomatic/quizx"
license-file = "LICENSE"
