[workspace]
resolver = "2"
members = ["quizx", "pybindings", "superopt"]
default-members = ["quizx"]

[workspace.dependencies]
quizx = { path = "./quizx" }
num = "0.3.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"

[workspace.package]
version = "0.1.0"
authors = ["Aleks Kissinger <aleks0@gmail.com>"]
edition = "2021"
rust-version = "1.75"
homepage = "https://github.com/Quantomatic/quizx"
license-file = "LICENSE"
